---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dntskdev/terraform
      environment:
        TF_VERSION: '0.12.25'
      build_args_from_env:
        - TF_VERSION
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
